apiVersion: v2
description: Hephy Workflow
home: https://github.com/researchbase/helm-charts
maintainers:
- name: Adam Meehan
  email: info@researchpath.com.au
name: workflow
version: v2.23.3
dependencies:
  - name: builder
    version: "v2.13.8"
  - name: slugbuilder
    version: "v2.8.1"
  - name: dockerbuilder
    version: "v2.8.4"
  - name: controller
    version: "v2.22.2"
  - name: slugrunner
    version: "v2.7.1"
  - name: database
    version: "v2.7.7"
  - name: fluentd
    version: "v2.15.3"
  - name: redis
    version: "v2.4.3"
  - name: logger
    version: "v2.5.2"
  - name: minio
    version: "v2.4.6"
  - name: monitor
    version: "v2.11.3"
  - name: nsqd
    version: "v2.5.2"
  - name: registry
    version: "v2.6.2"
  - name: registry-proxy
    version: "v1.5.2"
  - name: registry-token-refresher
    version: "v1.2.3"
  - name: router
    version: "v2.19.1"
  - name: workflow-manager
    version: "v2.6.3"
