{{ if .Values.global.experimental_native_ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "controller-api-server-ingress-http"
  labels:
    app: "controller"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
{{- if .Values.ingress_class }}
  ingressClassName: {{ .Values.ingress_class }}
{{- end }}
  rules:
  - host: deis.{{ .Values.platform_domain }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: deis-controller
            port:
              number: 80
{{- end }}
