apiVersion: v2
description: Git server and application builder for Hephy Workflow.
home: https://github.com/teamhephy/builder
maintainers:
- name: Adam Meehan
  email: info@researchpath.com.au
name: builder
version: v2.13.7
