apiVersion: v2
description: A kubernetes based docker image for running nsq daemon.
home: https://github.com/teamhephy/nsqd
maintainers:
- name: Adam Meehan
  email: info@researchpath.com.au
name: nsqd
version: v2.5.1
