apiVersion: v2
description: A PostgreSQL database used by Hephy Workflow.
home: https://github.com/teamhephy/postgres
keywords:
- database
- postgres
maintainers:
- name: Adam Meehan
  email: info@researchpath.com.au
name: database
version: v2.7.6
